<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-02-06 12:47

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.1.5 on 2025-02-06 15:30

>>>>>>> 8a843e03b60a090538fab496061704e42bbc4570
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 8a843e03b60a090538fab496061704e42bbc4570
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.TextField()),
                ('educacion', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
<<<<<<< HEAD
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 8a843e03b60a090538fab496061704e42bbc4570
            ],
            options={
                'db_table': 'candidato',
            },
        ),
    ]
