# Generated by Django 5.1.5 on 2025-02-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.TextField()),
                ('educacion', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
            ],
            options={
                'db_table': 'candidato',
            },
        ),
    ]
