# Generated by Django 5.1.5 on 2025-02-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidato',
            table='candidato',
        ),
    ]
