# Generated by Django 5.1.5 on 2025-01-28 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reclutador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('salario', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('id_reclutador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclutador.recruiterprofile')),
            ],
        ),
    ]
