# Generated by Django 5.1.5 on 2025-02-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='titulo',
            field=models.CharField(default='Titulo oferta', max_length=255),
        ),
    ]
