# Generated by Django 5.1.5 on 2025-02-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_oferta_titulo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oferta',
            table='oferta',
        ),
    ]
