# Generated by Django 5.1.5 on 2025-02-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_customuser_company_name'),
    ]

    operations = [
    ]
