# Generated by Django 5.1.5 on 2025-02-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20250204_1742'),
    ]

    operations = [
    ]
