<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-02-06 12:47

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.1.5 on 2025-02-06 15:30

>>>>>>> 8a843e03b60a090538fab496061704e42bbc4570
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 8a843e03b60a090538fab496061704e42bbc4570
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
<<<<<<< HEAD
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 8a843e03b60a090538fab496061704e42bbc4570
            ],
        ),
    ]
