# Generated by Django 5.1.5 on 2025-02-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id_aplicacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.TextField()),
            ],
        ),
    ]
