# Generated by Django 5.1.5 on 2025-02-06 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_initial'),
        ('candidato', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacion',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.candidato'),
        ),
    ]
